### ISSUE TITLE
Data File Timing Sync Issue

### ISSUE THREAD

**Issue by RingoHHuang** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#12]
Hi all,

I’m encountering some time synchronizing inconsistencies between the computer generated timestamp and the EyeTribe timestamps in the data output file. The logging messages in the eye data file seem to be marking rows earlier than the corresponding EyeTribe timestamp. I've attached a copy of the data output file below. The timestamp (first column) for the log messages doesn't match the time (second column).

I’m not too familiar with TC/PIP, so pardon any inaccuracies in my statements, but there may be a persistent backlog in writing each line of EyeTribe data to the file while the message logs sent from the Matlab experiment are editing the file in real time.

I manually checked the timestamps that marked different events, and the computer timestamps associated with each message log seems to be consistent with when I sent the messages. If that is indeed the case, a temporary, inelegant hack would be to sort the computer timestamps in ascending order. The message logs should then mark the correct time position in the eye data file.

Of course, it is more than possible that I am overlooking an error on my part in implementing the toolbox to my experiment, so please correct me if I’m missing something obvious. Any help would be greatly appreciated!

Thanks,
Ringo

[EyeTribeData_Sub99.xlsx](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/files/362386/EyeTribeData_Sub99.xlsx)

**Comment by esdalmaijer** [comment]
Hi Ringo,

Thanks for flagging this up! I just updated the underlying Python code (in [this commit](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/commit/041789b6bc6a93a6861eb87e7171e91d3ced7339), which should reduce the sampling lag. Would you mind giving this version a try, and reporting back on the results?

Also, thanks for providing that log file! Very helpful for debugging :)

Cheers,
Edwin

**Comment by RingoHHuang** [comment]
Hi Edwin,

Thanks so much for your prompt response and the update! The updated version works brilliantly, and the sampling lag is indeed reduced. I’ve attached the new log file, and you can see that the two timestamps from the messages line up with neighboring data much more accurately compared to the previous log file.

Thanks again, and I really appreciate all the work you put into this toolbox!

Best,
Ringo 

[EyeTribeData_Sub117.xlsx](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/files/364853/EyeTribeData_Sub117.xlsx)

**Comment by esdalmaijer** [comment]
Thanks for testing that so quickly, and for the compliments :)

Closing this issue for now, but please do feel free to reopen it (or to open a new one) when things go awry again.

Cheers,
Edwin
