### ISSUE TITLE
Can't initialise the EyeTribe in Mac OSX

### ISSUE THREAD

**Issue by localsign** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#13]
Hiya,
Thanks for the EyeTribe Toolbox. I'm trying to set it up in Matlab on my iMac and having trouble getting things initialised.

When I follow the instructions for "USAGE ON OS X AND LINUX" I open Terminal, cd to the folder where the python scripts are, but when I type the second command "python EyeTribe_Matlab_server.py" I get the following error:

Traceback (most recent call last):
  File "EyeTribe_Matlab_server.py", line 6, in <module>
    from pytribe import EyeTribe
  File "/Users/.../python_source/pytribe.py", line 16, in <module>
    from pygaze.py3compat import *
ImportError: No module named pygaze.py3compat

The python scripts are in that folder, as downloaded from here, but a part of that seems to be missing - are there additional files needed for this?

I'm running Mac OSX 10.9.5 on an iMac. I can activate the EyeTribe via their server (downloaded with their SDK) and calibrate using their software, so it's not a problem with the EyeTribe itself. Likewise on my machine Matlab and the Psychtoolbox both run fine (though this obviously isn't an issue here). I'm not so good with peripheral devices though so apologies if this is a daft question. Any pointers appreciated - thanks!

**Comment by esdalmaijer** [comment]
Thanks! Very good point. Should be fixed now. Would you mind downloading the newest version, and confirming whether it works for you?

**Comment by localsign** [comment]
Thanks! At first I got the same error, just needed to delete line 16 from pytribe.py (which is still there in the current version). Now I can get Matlab to open up the server, not yet able to get the calibration running but I'll give it another try soon.

**Comment by esdalmaijer** [comment]
Not sure what you mean by "current version". Line 16 is still there, but it now imports a local version of py3compat (as you can see in the current version, [here](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/blob/master/python_source/pytribe.py#L16)). Are you sure you updated, and/or that the error was exactly the same?

PS: This does mean you also need said version of py3compat, which is now included in the Python source (see [here](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/blob/master/python_source/py3compat.py)). Maybe you missed that, and didn't download it yet?
