### ISSUE TITLE
Failed to initialize EyeTribe object in the Server. OSX 10.11.4. Matlab R2015b

### ISSUE THREAD

**Issue by guillermosolovey** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#14]
Thanks for the Toolbox! I am having the following issue when running the example script. 

on Matlab:

> > [success, connection] = eyetribe_init('test');
> > Opening new connection.
> > Sending socket initialization message.
> > success
> > Server says: success
> > Sending socket initialization message.
> > Server says: ERROR in Initialize EyeTribe: could not initialize new EyeTribe object.
> > Failed to initialize EyeTribe object in the Server.

on the Terminal:
$ python EyeTribe_Matlab_server.py
Starting new socket connection (ip=localhost, port=5670).
Listening for connections...
Found new connection (127.0.0.1, 50959)
Client says: Hi, this is Matlab!
ERROR in Initialize EyeTribe: could not initialize new EyeTribe object.

Any idea what's wrong? Thank you!

**Comment by esdalmaijer** [comment]
Thanks for your feedback!

The issue is with initialising an EyeTribe instance, which means that the issue occurs in the [initialisation part](https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/blob/master/python_source/EyeTribe_Matlab_server.py#L172) of the custom server.

One thing I notice, is that you changed the port number for the socket connection between Matlab and the custom server. Did you do this on purpose? Could it be that the EyeTribe port was also changed? (As it currently is, the custom server expects it to be at the default port of 6555.)

Also, it would help if you could provide some additional info: 1) What OS are you using? 2) Are you using the most recent version of the toolbox? (If you're unsure, download it now, and check if it works.) 3) Did you make any customisations to the toolbox?

**Comment by localsign** [comment]
Was this ever resolved? I'm finally back at trying to get this to work on my mac and not having much luck. When I run EXAMPLE.M I get the following output in the terminal:

> Starting new socket connection (ip=localhost, port=5666).
Listening for connections...
Found new connection (127.0.0.1, 49966)
Client says: Hi, this is Matlab!
ERROR in Initialize EyeTribe: could not initialize new EyeTribe object.

Matlab gives the following:
> Opening new connection.
Sending socket initialization message.
success
Server says: success
Sending socket initialization message.
Server says: ERROR in Initialize EyeTribe: could not initialize new EyeTribe object.
Failed to initialize EyeTribe object in the Server.
Error using fwrite
Operation is not implemented for requested file identifier.
>
>Error in eyetribe_send_command (line 17)
fwrite(connection, command);
>
>Error in eyetribe_start_recording (line 14)
message = eyetribe_send_command(connection, 'Start recording');
>
>Error in EXAMPLE (line 12)
success = eyetribe_start_recording(connection);

I notice your comment above that the port should be 6555 - the variation above (5666) seems to derive from eyelink_init.m line 18, whereas the python code does use 6555. I've tried various combinations of these numbers in the two files though and get the same errors. The toolbox just doesn't seem to be able to initialise the Eyetribe objects in the server. 

I'm running Mac OS X 10.11.6 on a Mac Pro, using Matlab 2016a. I've tried modifying the toolbox but the above output comes from a fresh install of it, downloaded today. Any thoughts appreciated!

**Comment by localsign** [comment]
Ah! Never mind - I found the solution in a closed issue. For the record the solution was to open the Eyetribe SDK, then in a new instance of terminal initiate the server via the python commands, then run the matlab script.  

Comment in question is from HannahHMK here: https://github.com/esdalmaijer/EyeTribe-Toolbox-for-Matlab/issues/9
>Hi Edwin, I met a few people this week who are also using your scripts to get  their EyeTribes running and indeed they ran into the same problem (Mac  users). Can I add this part about starting the EyeTribe executable over  terminal in MacOS to your documentation? I think it would make it very  simple for many users to get started. Or maybe it is easier if you add it? Here is an example text:  Go to the EyeTribe folder from the EyeTribe SDK and start the  EyeTribe executable simply by double clicking on it. It will open up a  Terminal window. (Or you can open it directly in Terminal via  /Applications/EyeTribe/EyeTribe) Open a new, additional tab in Terminal. Use the cd function to go to your python_source folder. An example:  cd /home/python_source   Use Python to run the source. Python should be installed on any  Linux system, and I think OS X usually comes with it as well. Type the  following command in the Terminal:  python EyeTribe_Matlab_server.py   Now run your Matlab script (but do it within two minutes of starting the Python script, because it will time out after that).
--
