### ISSUE TITLE
Rerunning calibration -> "Failed to obtain results"

### ISSUE THREAD

**Issue by knaeckebrot0815** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#2]
Dear Edwin, 

Rerunning a calibration from within PTB invariably results in a "Failed to obtain results." error, and accuracy of the second calibration attempt is not shown.

The problem seems to be that sending 
message = eyetribe_send_command(connection, 'Calibration start')
a second time is not possible.

Try for example:
[success, connection] = eyetribe_init('test');
message = eyetribe_send_command(connection, 'Calibration start'); --> 'success'
message = eyetribe_send_command(connection, 'Calibration finished'); --> 'success'
message = eyetribe_send_command(connection, 'Calibration start'); --> 
'ERROR in Calibration start: failed to start calibration.'

Hartelijk bedankt!!

%---------------------------------------------------------------------------------------------

Command prompt reads>
...
Starting calibration.
Server says: success
Failed restart calibration mode.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to start new point.
Failed to end point.
Failed to obtain results.
Failed to exit calibration mode.
...

Machine1
MATLAB Version: 8.2.0.701 (R2013b)  64bit
Operating System: Microsoft Windows 7 Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
Psychtoolbox Version: 3.0.11 
EyeTribe Software Version: 0.9.49 (most recent), Firmware 293

Machine2
MATLAB Version: 8.0.0.783 (R2012b)
MATLAB License Number: 303238
Operating System: Microsoft Windows 7 Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
Psychtoolbox Version: 3.0.11 beta and 3.0.12 beta
EyeTribe Software Version: 0.9.41, Firmware 293

**Comment by esdalmaijer** [comment]
Good point; I've recently encountered this on a PC in one of our labs too. I seem to remember solving it; will report back if I did.

**Comment by knaeckebrot0815** [comment]
Dear Edwin, 

That would be great, thanks. I was unable to find the problem. 

Best regards

**Comment by saltthehash** [comment]
I have also been having this exact problem. I tried adding a function to the sub-server to clear the current calibration to see if that would help but it didn't. The only workaround that finally seemed to do the trick was simply writing some code to close the connection, restart the server, and start over again. I've been trying to figure out what could possibly be causing this but I can't seem to find it. I tried raising an exception in the calibration command and got this:

```
Client says: Calibration start
Traceback (most recent call last):
  File "EyeTribe_Matlab_server.py", line 201, in <module>
    tracker.calibration.start(pointcount=16) #Changed pointcount to 16
  File ".../EyeTribe/pytribe.py", line 1121, in start
    response = self.connection.request('calibration', 'start', {'pointcount':pointcount})
  File "…/EyeTribe/pytribe.py", line 402, in request
    elif self.resplist[i]['request'] == request:
KeyError: 'request'
logout
[Process completed]
```

**Comment by BeibinLi** [comment]
I have the same problem. Anyone has a solution now? My computer could start the calibration, but I received "Failed to end point. Failed to start new point" once I got into calibration.

My Eye Tribe server said "cannot parse message 'Calibration pointstart;x=..., y...' "

Thank you!

**Comment by onlyhakanboz** [comment]
Dear All;

Could you please share a video how to use EyeTribe-Toolbox-for-Matlab. I will be really appreciate to you.

Best wishes

Hakan

**Comment by BeibinLi** [comment]
I tried to install the package on another Windows 7 computer, and it works fine. The problem only occurs in my Windows 8 computer. So, I guess this problem is related to Operation System. 

@onlyhakanboz   Sorry, I don't have a video tutorial, but it's easy to install the package. First, you need to install PsychToolBox at http://psychtoolbox.org/download/   and this is the most tediou step (tips: you should install everything the page suggested, e.g. GStreamer). Then, you can install this EyeTribe-Toolbox-for-Matlab by following readme.md file. At last, you can copy and paste the sample code (from readme) to Matlab.

**Comment by knaeckebrot0815** [comment]
Any news on this Edwin?

**Comment by nikaadamian** [comment]
Had the same problem, resolved with the help of the suggestion in the issue #8 (thanks @DavCling !)

**Comment by esdalmaijer** [comment]
This issue should be solved in the newest commit, with the exception of the problem flagged up in issue #8  (which will be dealt with shortly). Please do reopen this issue (or open a new one) if any calibration issues persist.
