### ISSUE TITLE
eyetribe_init

### ISSUE THREAD

**Issue by ejc557** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#6]
Hi everyone,
I have just received my Eye Tribe eye tracker and I am trying to use the MATLAB toolbox but I am having difficulties.
The example.m script fails straight away with the 'eyetribe_init' command. It comes up with an error saying:

??? Undefined function or method 'tcpip' for input arguments of type 'char'.

Error in ==> eyetribe_init at 18
connection = tcpip('localhost', 5666);

Error in ==> EXAMPLE at 9
[success, connection] = eyetribe_init('test');

Please help, thank you!

**Comment by esdalmaijer** [comment]
Handled via email, answer:

The [tcpip function](http://se.mathworks.com/help/instrument/tcpip.html) is part of the [Instrument Control Toolbox](http://se.mathworks.com/products/instrument/supported/tcp-ip.html). Could it be that your Matlab installation does not include this? The error message you're getting seems to indicate this: said function is not defined (that is: it is unknown to Matlab at this point).

Some necessary information: Matlab installations do not necessarily include all optional 'toolboxes'. These provide additional (somewhat separate) functionality, and tend to cost extra.
