### ISSUE TITLE
psize incorrect when signal for one eye is lost

### ISSUE THREAD

**Issue by knaeckebrot0815** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#7]
I noticed that in the .tsv files psize is calculated as (Lpsize + Rpsize)/2 even if tracking of one eye fails. It would make more sense to report the psize of the tracked eye instead.

**Comment by esdalmaijer** [comment]
Sorry, forgot to reply to this. Issue should be solved since a few commits ago :)
